### PR TITLE
fix parseAddrPort error

### LINKED ISSUE #79: kubevpn connect --ssh-addr error desc = not an ip:port
It looks like even if all ssh configuration correct, it failed with below error. 
```
kubevpn connect --ssh-addr 192.168.1.100:22 --ssh-username root --ssh-keyfile ~/.ssh/ssh.pem --foreground=true
Error: rpc error: code = Unknown desc = not an ip:port
```

ahd kubevpn logs or debug=true does not generate any logs.

### PR DESCRIPTION
**Pull request by whomobile**
add server url with dns name and port case. 

fix #79 issue.

### CODE REVIEW

**Review by wencaiwulue — APPROVED** [review]
Brilliant

File: pkg/handler/connect.go [hunk 1]
```diff
@@ -827,11 +827,39 @@ func SshJump(ctx context.Context, conf *util.SshConfig, flags *pflag.FlagSet, pr
...
+		}
+	}
+	ips, err := net.LookupHost(serverHost)
+	if err != nil {
+		// handle error
+		return
+	}
+
+	if len(ips) == 0 {
+		// handle error: no IP associated with the hostname
```
Comment (wencaiwulue) [inline pkg/handler/connect.go:851]: you can generate a new error, like `err = fmt.Errorf("no IP associated with the hostname %s", serverHost)`

**Review by wencaiwulue — APPROVED** [review]
